export { PreparacionStep } from "./PreparacionStep";
export { DisenoStep } from "./DisenoStep";
export { CorteStep } from "./CorteStep";
export { PulidoStep } from "./PulidoStep";
export { BarrenosStep } from "./BarrenosStep";
export { MarcaStep } from "./MarcaStep";
export { SerigrafiaStep } from "./SerigrafiaStep";
export { TempladoStep } from "./TempladoStep";
export { ObservacionesStep } from "./ObservacionesStep";
